/* import type { Metadata } from 'next'; */
import LayoutWrapper from './LayoutWrapper';
import Providers from '@/components/providers';
import '@/assets/scss/globals.scss';
import 'simplebar/dist/simplebar.min.css';
import "slick-carousel/slick/slick.css";
import "slick-carousel/slick/slick-theme.css";

/* const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}; */

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body>
                <Providers>
                    <LayoutWrapper>{children}</LayoutWrapper>
                </Providers>
            </body>
        </html>
    );
}
