import type { Metadata } from "next";
import Providers from "./components/providers";
import LayoutWrapper from './pages/LayoutWrapper';
import "./assets/scss/globals.scss";
import 'simplebar/dist/simplebar.min.css';

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  	children,
}: Readonly<{
  	children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      	<body>
        	<Providers>
          		<LayoutWrapper>{children}</LayoutWrapper>
        	</Providers>
      	</body>
    </html>
  );
}
