name: Firebase Deploy

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "20"

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_POETRY }}

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Clean Up Old Build Artifacts
        run: |
          rm -rf client/.next
          rm -rf client/public

      - name: Install Dependencies and Build Frontend (Client)
        run: |
          cd client
          npm install --legacy-peer-deps
          npm run build

      - name: Ensure Public Directory Exists
        run: mkdir -p client/public

      - name: List Client Build Directory
        run: ls -la client/.next

      - name: Copy Next.js Build to Functions Directory
        run: |
          cp -R client/.next functions/.next
      
      - name: Install Dependencies and Build Backend (Server)
        run: |
          cd server
          npm install --legacy-peer-deps
          npm run build
      
      - name: Install Dependencies and Build Firebase Functions
        run: |
          cd functions
          npm install --legacy-peer-deps
          npm run build
      
      - name: Deploy to Firebase
        run: firebase deploy --only hosting,functions --project poetry-a6f93
