name: Deploy to Firebase Hosting on merge

on:
  push:
    branches:
      - master

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"

      - name: Print Commit Hash
        run: git rev-parse HEAD

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Install Dependencies and Build Frontend (Client)
        run: |
          cd client
          npm install --legacy-peer-deps
          npm run build

      - name: List Client Build Directory
        run: ls -la client/.next

      - name: Copy Next.js Build to Functions Directory
        run: |
          cp -R client/.next functions/.next
      
      - name: Install Dependencies and Build Backend (Server)
        run: |
          cd server
          npm install --legacy-peer-deps
          npm run build

      - name: List Server Build Directory
        run: ls -la server/dist

      - name: Install Dependencies and Build Firebase Functions
        run: |
          cd functions
          npm install --legacy-peer-deps
          npm run build

      - name: List Functions Build Directory
        run: ls -la functions/lib

      - name: Deploy to Firebase
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_POETRY }}
          channelId: live
          projectId: poetry-a6f93
